version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      midnight-sdk:
        patterns:
          - "@midnight-ntwrk/*"
      dev-tools:
        patterns:
          - "typescript"
          - "tsx"
          - "esbuild"
